### ISSUE TITLE
Does not require files from paths

### ISSUE THREAD

**Issue by bisubus** [ivogabe/small#1]
I stumbled upon a problem. The files cannot be required from anywhere but current source folder. E.g. `./folder/filewithoutext` gives 

> Reference not found:

And `./filewithoutext` works fine.

The same concerns packages from `node_modules`, they cannot be required by their names (and by relative paths as well). I was under impression that sometimes they were required (other build errors appeared but 'Reference not found' didn't) but it never was consistent. It seems that at some level the files are cached, so the changes to bundle files don't come into effect immediately.

Gulp 3.9.0, Node 4.2.1, Windows 7

It is a wonderful little tool in other respects.

**Comment by ivogabe** [comment]
Can you give some more information? I've used small on projects with (sub)directory structure. Can you share your gulpfile and directory structure?

Since you're using Windows, there might be an issue with slashes (as Windows uses backslashes (\) instead of forward ones (/) used on Linux and Mac). Can you debug to see whether there is an inconsistency with these slashes?

**Comment by bisubus** [comment]
Here's a branch I've created for this purpose
https://github.com/ex-machine/ng-classified/tree/small

I think I've tracked the problem down.
All of [these](https://github.com/ex-machine/ng-classified/blob/small/src/ng-classified.js#L3) requires are working fine a long as the paths for them were supplied via [gulp.src](https://github.com/ex-machine/ng-classified/blob/small/gulpfile.js#L26). The documentation was very modest on that, but it looks like the assumption that it would just resolve resolve paths (like Node require does) was wrong.

**Comment by ivogabe** [comment]
I think you need to add `externalResolve: ['node_modules']` to the options object in your gulpfile. I saw that option is not present in the readme, I'll add it there.

**Comment by bisubus** [comment]
Thank you, works like a charm. It is great to have a neater alternative to Webpack for smaller projects where extra few bytes matter.
